- name: Installer et configurer nginx
  hosts: web
  become: yes

  tasks:
    - name: Installer nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copier index.html
      copy:
        src: files/index.html
        dest: /var/www/html/index.html

    - name: Copier style.css
      copy:
        src: files/style.css
        dest: /var/www/html/style.css

    - name: Copier script.js
      copy:
        src: files/script.js
        dest: /var/www/html/script.js

    - name: Démarrer nginx
      service:
        name: nginx
        state: started
        enabled: yes
