- name: Installer et configurer nginx
  hosts: web
  become: yes

  tasks:

    - name: Installer nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copier la page HTML
      copy:
        src: files/index.html
        dest: /var/www/html/index.nginx-debian.html

    - name: Copier le fichier CSS
      copy:
        src: files/style.css
        dest: /var/www/html/style.css

    - name: Copier le fichier JS
      copy:
        src: files/script.js
        dest: /var/www/html/script.js

    - name: Démarrer nginx
      service:
        name: nginx
        state: started
        enabled: yes